language: node_js
node_js:
  - "stable"
sudo: true
dist: trusty

install:
  - yarn

branches:
  only:
  - master

before_script:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get clean
 - sudo apt-get update
 - sudo apt-get install dpkg
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb

script: 
  # - ng test --watch false --karma-config './src/karma.conf.js'
  # - npm run webdriver-update-ci
  # - npm run e2e --webdriver-update=false
  - ng build --prod --c=prod

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "matthewabbas.com"
  skip_cleanup: true
  region: "us-east-2"
  local_dir: dist/portfolio
  on:
    branch: master
